### ISSUE TITLE
Support for YOLOv10

### ISSUE THREAD

**Issue by 2gunsu** [hailo-ai/hailo_model_zoo#106]
Hello!
I am wondering if there are any plans to support the YOLOv10 model, which is the most recent model.
(https://github.com/THU-MIG/yolov10)
Thank you.

**Comment by omerwer** [comment]
Hi @2gunsu,
Yes, the Yolov10 architecture is planned to be supported in the upcoming release (July release).

Regards,

**Comment by 2gunsu** [comment]
Thank you for your answer.
Have a nice day!
