### ISSUE TITLE
The benchmark of "yolov7.hef" is much slower than the official report on website .

### ISSUE THREAD

**Issue by HuiJu1218** [hailo-ai/hailo_model_zoo#118]
I correctly converted yolov7 from float32 to an int8 HEF and inference on hailo-8, but when I used the benchmark, I found that my model's FPS (28FPS) is only half of the official benchmark (46FPS).The official benchmark info can be found from [here](https://hailo.ai/products/hailo-software/model-explorer/). I actually want to confirm whether the model information I converted is correct. Thanks.
1. What does 'vstream info' represent?
2. Why is the output showing as float32 instead of int8? 
3. Also, is there any place that provides the official yolov7.hef or a complete guide on the conversion process?
Below are the results I obtained from using the `benchmark` and `parse-hef` commands in `hailortcli`.
![parse_hef](https://github.com/user-attachments/assets/735fa3b4-4e30-451f-ae1b-ed2ccf786e4b)
![benchmark](https://github.com/user-attachments/assets/4c7468cc-36bb-402a-844e-954e20b63d56)

**Comment by omerwer** [comment]
Hi @HuiJu1218,
What platfrom are you running it on (CPU etc.)? how many lanes does your PCIe have?
You can check the first using `lscpu` and the second with `lspci -vv`

Regards,

**Comment by HuiJu1218** [comment]
Hi! @omerwer , thank you for your response. The issue has been resolved. I used `lspci -vv` to check my platform and found out that the PCIe can only operate at Gen3 x1, not Gen3 x2. After switching to another platform and confirming that it could support Gen3 x2 speeds, the FPS I measured matched the official data.

Thanks.
