### ISSUE TITLE
Old version of yolov5 in retraining docker container.

### ISSUE THREAD

**Issue by frenky-strasak** [hailo-ai/hailo_model_zoo#32]
Hi,
for what reason does the retraining docker container contain the old version of yolov5 v2.0? Is possible to use some new versions of yolov5 such as v6.2? Are these newer versions of yolov5 compatible with data flow compiler to optimize and compile models to hailo hef files?
Thanks!

**Comment by nadaved1** [comment]
Hi Frenky,
Newer versions of yolov5 are also supported by the tools.

בתאריך יום ד׳, 9 בנוב׳ 2022, 16:20, מאת Frenky Střasák ‏<
***@***.***>:
