### ISSUE TITLE
Reactangle hef model does not work

### ISSUE THREAD

**Issue by frenky-strasak** [hailo-ai/hailo_model_zoo#43]
Hi,
in the yolov5 retraining container (v.2) I have exported `yolov5m_wo_spp.pt` to ONNX with rectangular shape:
` python models/export.py --weights model.pt --img 352 640 --batch 1` (--img H W)

Then I compiled this onnx model: 
`hailomz compile --ckpt model.onnx --calib-path calib_dataset --yaml yolov5m_wo_spp.yaml`
where I changed the `yolov5m_wo_spp.yaml` like this:

-  I added the `preprocessing` part with corresponding shape:

```
preprocessing:
  network_type: detection
  input_shape:
  - 352
  - 640
  - 3
```
- and I changed the `info` (the output shapes were found by Netron tool) 
```
info:
  input_shape: 352x640x3
  output_shape: 11x20x18, 22x40x18, 44x80x18
```
The complete file is here: [yolov5m_wo_spp.zip](https://github.com/hailo-ai/hailo_model_zoo/files/10197639/yolov5m_wo_spp.zip)

The compilation looks fine. When I deploy the **hef** file to my pipeline I can see wrong bboxes which are doubled and shifted. But they move in the same way as the object to be detected.

What do I miss? Should I also modify the **yolov5m_wo_spp.alls file**? Could you point me please?
Thank you!

**Comment by nadaved1** [comment]
Hi Frenky,
Please check in the pt file if the anchors been changed. For example:

import torch m = torch.load("last.pt")["model"] detect = list(m.children())[
0][-1]
detect.anchors

Compare these to the anchors in the yaml file.

**Comment by frenky-strasak** [comment]
Hi @nadaved1,
thank you!
I checked it and the anchors are the same as, the original model `yolov5m_wo_spp.pt`:
```
tensor([[[ 1.25000,  1.62500],
         [ 2.00000,  3.75000],
         [ 4.12500,  2.87500]],

        [[ 1.87500,  3.81250],
         [ 3.87500,  2.81250],
         [ 3.68750,  7.43750]],

        [[ 3.62500,  2.81250],
         [ 4.87500,  6.18750],
         [11.65625, 10.18750]]], dtype=torch.float16)
```
However I exported two onnx models from the torch one. First model with 640x640 input shape which works after the compilation. Only the second one with 352x640 input shape does not work after the compilation.

Is my yaml file correct? 
Thank you!

**Comment by nina-vilela** [comment]
Hi @frenky-strasak, 

Could you please open a ticket through our website? 
https://hailo.ai/contact-customer-support/

That way we can assist you better
