### ISSUE TITLE
Where to find a list of supported operations?

### ISSUE THREAD

**Issue by sbudenkov** [hailo-ai/hailo_model_zoo#49]
Hi all,

I can't find a list of supported operations. I see only supported model architectures.

**Comment by nadaved1** [comment]
Hi @sbudenkov, this list would not be here, you need to look at the developer-zone documentation section. The Dataflow compiler user guide has it.

**Comment by sbudenkov** [comment]
@nadaved1 
Thank you very much. I suggest to add a note about that to the main github page.
