### ISSUE TITLE
Can the Yolov8 model trained using retraining commands be used for closed-source commercial purposes?

### ISSUE THREAD

**Issue by ryan-minato** [hailo-ai/hailo_model_zoo#61]
I am using Hailort and Model Zoo in a closed-source project, both of which are released under the MIT license. However, I still have some questions about the licensing.
As far as I know, starting from Yolov5, many yolo-vx models have been released under the [AGPL 3.0 license](https://github.com/ultralytics/yolov5/blob/master/LICENSE). 
Will models re-trained using the hailo model zoo also inherit the AGPL 3.0 license, or am I allowed to integrate them into a closed-source commercial project?

**Comment by nadaved1** [comment]
Hi @minato-ellie, the retraining docker inherirt it's licenses from the respective original repos
