### ISSUE TITLE
YOLOv8 model transformation for a custom dataset

### ISSUE THREAD

**Issue by pcycccccc** [hailo-ai/hailo_model_zoo#85]
Hello, I am trying to convert my trained YOLOv8 model into a hef file. I am reading the related hailo model zoo file to figure out the documents and processes that need to be prepared.
As far as I know,
（1）Prepare an onnx model trained on my own dataset
（2）networks/yolov8.yaml(need to be modified according to the actual situation, please refer to)
（3）-calib-path path to the image dataset (does this copy the images to a folder ahead of time?)
I can get the hef model by executing the command, but I learned that to optimize and compile the model, I also need to generate the TFRecord file. Is this necessary? I have a few questions:
（1）Is TFRecord related to the third step, calib-path? How to relate?
（2）What types of files do I need to prepare in advance, an image set and a tag set? Should the tags be in xml or yolo's txt format
（3）Which py file should be run to create the TFRecord file? Do need to change any other parameters?

**Comment by tmyapple** [comment]
Hi @pcycccccc 

- For compilation of the model you don't need a TFRecord file. The TFRecord used are a serialization of open datasets, which you can reproduce using create scripts (see docs/DATA.rst for more information). It is useful for testing on benchmark datasets (i.e. coco for detection ..)
- Calibration should be performed on your own dataset - you should create a directory with sample of your images, and use --calib-path to point there.
`hailomz compile --ckpt <path-to-your-onnx> --calib-path </path/to/calibration/imgs/dir/> --yaml <yaml_file_path> `
Regarding the **YAML** - preferably use a YAML corresponds to the yolov8 variant you chose, for minimal amount of changes.
In case you have changed them model structure, then the start node and endnodes of the model might be changed... and can be modified through the YAML:
`nodes: [null , ["1st-end-node-name", "2nd-end-node-name" ... , "nth-end-node-name"]]`
If you just retrained a model on your own dataset, the start/end nodes expected to stay the same and using the correspond variant YAML will work

**Comment by pcycccccc** [comment]
@tmyapple Thank you for your answer, I roughly understand, but I would like to ask: Does calib-path need to prepare an annotation file for calibration? Just provide the image set?
