### ISSUE TITLE
yolov8s model optimization process error: ValueError: 'yolov8' is not a valid NMSMetaArchitectures

### ISSUE THREAD

**Issue by pcycccccc** [hailo-ai/hailo_model_zoo#86]
I am following the tutorial to optimize the files that have been converted to har. The model I am using is YOLOv8s model trained on trench, which can correctly output har files during parsing, but it gives an error when running Optimiz: ValueError: 'yolov8' is not a valid NMSMetaArchitectures. My Parsing command is:
`hailomz parse --ckpt /root/My_v8_data/model/Groove_v8s.onnx --hw-arch hailo8 yolov8s`
MY Optimiz command is:
`hailomz optimize yolov8s --har /root/Groove_v8s.har --calib-path /root/My_v8_data/image/Groove/ --performance`
The error is displayed as follows:
![image](https://github.com/hailo-ai/hailo_model_zoo/assets/108455796/ebf9a143-a5d4-47bd-a9fa-c51b21f69193)

**Comment by nadaved1** [comment]
Which DFC and MZ versions are you using?

בתאריך יום ב׳, 1 באפר׳ 2024, 09:06, מאת pcycccccc ***@***.***

**Comment by pcycccccc** [comment]
@nadaved1 
I'm using 

- **Hailo-Dataflow**: hailo_dataflow_compiler-3.24.0-py3-none-linux_x86_64.whl
- **hailo-model-zoo**: I git clone (latest version: master) directly from the github project and installed it in hailo-dataflow.

**Comment by nadaved1** [comment]
Yolov8 NMSmode support was added on 3.26. Is it optional to uprev to that?

בתאריך יום ב׳, 1 באפר׳ 2024, 12:27, מאת pcycccccc ***@***.***

**Comment by pcycccccc** [comment]
@nadaved1 Thanks for the advice, I will try to upgrade the version before doing the model transformation.

**Comment by pcycccccc** [comment]
@nadaved1 I reinstalled hailo-dataflow as you said, and the nms issues disappeared during the optimization process, but the dataset issues did appear: SubprocessFailure. The Dataset length check subprocess failed with exitcode 1. 
The error message is:
![a4e3b6d3b423b7fe98cc819d7c72898](https://github.com/hailo-ai/hailo_model_zoo/assets/108455796/068aa888-1f51-4cde-862d-5e2cf429832a)
![9aa28c8a548c08262d953e0a6231e20](https://github.com/hailo-ai/hailo_model_zoo/assets/108455796/19e58664-abcd-4e1c-ab8c-6c52f2a4dc6c)
What is the format of the data set required for the optimization process? The folder I originally specified only contained about 3000 images in a grayscale format with 1 channel.

**Comment by pcycccccc** [comment]
@omerwer hi, I want to confirm two questions:
 (1) Isn't MZ running under the virtual environment of DFC? Or are they separate environments? 
(2) I ran the model transformation of the above steps in the DFC environment some time ago (using the instructions of MZ). The difference is that I replaced the calibration data and the model (the yolov8n model trained on another dataset). I found that a jpg image in 3 channels can normally complete the hailomz optimize process, but the jpg image in 1 channel will give an error. I wonder, does the calibrated image have to be a 3-channel image? Is there an error for 1-channel images? When I used a 1-channel image, the calibration gave me an error: `Trying to decode BMP format using a wrong op. Use 'decode_bmp' or 'decode_image' instead. Op used: DecodeJpeg`

**Comment by omerwer** [comment]
Hi @pcycccccc,
(1) The MZ env requires to have the corresponding DFC packages installed, but it's not the case the other way around - the DFC can be installed to a clean env and work as a standalone tool.
(2) I'm not sure exactly what was you case, but if the model is trained with RGB images, then the calibset needs to be RGB, meaning (N,H,W,C) numpy array when running in DFC.
If the model was trained on grayscale images, then this is a bit more tricky as is standard np.save for grayscale images, the shape of the numpy array would be (N,W,H). This is why when saving a calibration set of grayscale for the DFC optimization step, the np.save should look like this:
np.save('calibset.npy', np.expand_dims(calib_np_array, axis=3))

Regards,
