### ISSUE TITLE
Are there any plans to add cpp examples for yolov8seg?

### ISSUE THREAD

**Issue by dongxuanlb** [hailo-ai/hailo_model_zoo#92]
I can found the python [examples](https://github.com/hailo-ai/Hailo-Application-Code-Examples/blob/main/runtime/python/instance_segmentation/yoloseg_inference.py),
is any plan to add cpp one?

**Comment by omerwer** [comment]
Hi @dongxuanlb,

Yes, it is planned for the future. We'll update here once it is done and loaded to the Hailo Applications repository.

Regards,
